### ISSUE TITLE
Proposal for Design Enhancement

### ISSUE THREAD

**Issue by mesalm** [NK-Works/SnapTalk#10]
First, I would like to thank you for sharing this amazing project. I found it very helpful and well-structured.

I have made a few design modifications to improve the overall look and user experience of the registration page, including some new animations, color adjustments, and input focus effects. I would like to get your feedback on whether these changes align with your vision for the project.

Here are the key changes I made:

    Added a typing animation for the sign-up header.
    Updated input fields' focus effects for a more modern look.
    Adjusted the background gradient to enhance readability and appeal.

If you find these enhancements useful, I would be happy to submit a pull request. Please let me know your thoughts!

Thank you for your time, and looking forward to your feedback
![screencapture-localhost-3000-2024-10-11-20_02_48](https://github.com/user-attachments/assets/819fb0a6-97c8-4405-9130-d9dd7bdacc98)

**Comment by NK-Works** [comment]
go ahead...
just make sure the ui is symmetric... before pulling a merge req

**Comment by mesalm** [comment]
Thank you for your response! I'll go ahead and make the UI adjustments to ensure it is symmetric. Once everything looks good, I'll submit the merge request for your review. Please let me know if there are any other preferences or details you'd like me to consider during the update

**Comment by mesalm** [comment]
Hi, I have submitted a pull request with the updates. I would appreciate it if you could review the changes, and if everything looks good, kindly merge it. Also, it would be great if you could add the 'hacktoberfest' label to the PR for the event. Thank you

**Comment by NK-Works** [comment]
merged
