### ISSUE TITLE
problem in uploading the files

### ISSUE THREAD

**Issue by lightning-sagar** [NK-Works/SnapTalk#18]
![image](https://github.com/user-attachments/assets/560b6cdf-fc60-488d-a0fc-d0cf9bd30bbb)

in this img there is problem in uploading the image,
is the input "file" field should be required?? if yes then we can just give him a alert that it is reuired, instead of this....
![image](https://github.com/user-attachments/assets/6b5c21f6-7e05-4445-8f5b-ae1633c6fe3b)

**Comment by NK-Works** [comment]
go ahead... looking forward to it:)
