### ISSUE TITLE
Major UI Rehaul!

### ISSUE THREAD

**Issue by NK-Works** [NK-Works/SnapTalk#24]
I am planning a major ui rehaul for the website tailoring it to be a proper social media site... like instagram...
We can divide the tasks in this rehaul into parts so that everyone can contribute...
Those interested can comment below....
For starters I am planning to make the UI like instagram...
you guys can now create a lot more new issues surrounding the frontend to make it better:)

**Comment by Prachirsh** [comment]
I would like to work on it includes a navigation bar, a home feed, a profile section, and a post card layout.
Can you assign it to me?

**Comment by NK-Works** [comment]
sure go ahead

**Comment by NK-Works** [comment]
more people can simultaneously work on this...
I need as many features as possible to i will assign this to multiple people.

**Comment by Aakansha-Chavan** [comment]
@NK-Works I am interested to contribute.

**Comment by NK-Works** [comment]
Assigned you as well... You can create a PR

**Comment by Aakansha-Chavan** [comment]
okay I will surely try my level best! As I am a beginner.
