### ISSUE TITLE
[ENHANCEMENT]: Improve Search Functionality

### ISSUE THREAD

**Issue by ash956901** [NK-Works/SnapTalk#4]
Would like to improve search funcitonality using regex. Right now you have to exactly type the username correct in order to get the user which decreases the user experience . I can add regex and make it better so as to show all the matches sorted by the number of matches they have . 

<img width="1440" alt="Screenshot 2024-10-11 at 7 16 35 PM" src="https://github.com/user-attachments/assets/6702c861-1cfc-4f12-a958-fc4bd0d39c1a">
<img width="1440" alt="Screenshot 2024-10-11 at 7 16 51 PM" src="https://github.com/user-attachments/assets/ef510599-4c33-405e-9327-9d4b120a9748">
<img width="1440" alt="Screenshot 2024-10-11 at 7 16 59 PM" src="https://github.com/user-attachments/assets/5dfcc508-fbb6-4db0-9fe3-4d9c928e1b92">

**Comment by ash956901** [comment]
Assing this to me and add hacktober tag please

**Comment by NK-Works** [comment]
go ahead i am looking forward to what you will build:)

**Comment by ash956901** [comment]
@NK-Works aye aye captain
