### ISSUE TITLE
removing read more for better user interface

### ISSUE THREAD

**Issue by SanidhyaSharma28** [NK-Works/SnapTalk#8]
instead of adding read more button make it render when clicked on the artefact card anywhere
please assign me this

**Comment by NK-Works** [comment]
go ahead and implement...
I am looking forward to your contribution...

**Comment by SanidhyaSharma28** [comment]
heya please check i have removed the read more button and now you can just click on the card to pop it up instead of read more button

**Comment by NK-Works** [comment]
merged
